### ISSUE TITLE
Including files with absolute path on mixed Windows/Linux environments

### ISSUE THREAD

**Issue by Nibbler73** [jlolling/talendcomp_tContextInput#1]
I'm implementing the fabulous component `tContextInput` to include configuration files with access credentials.

It works great, but since I develop on Windows and have the JobServer on Linux I need to declare my includes twice.

E.g. in a property file like `databaseConnections.properties` I write:

```
file_manageSchema1=/var/opt/talend/etl/config/manage.dev
file_manageSchema2=\\var\\opt\\talend\\etl\\config\\manage.dev
```

`file_manageSchema1` will load the file only on Linux, while `file_manageSchema2` will load it only on Windows. The total result is as desired.

Would be great if path-translation of includes could work the same way as paths given in Talend generally. e.g. the `file_manageSchema1` path would internally be translated to the Windows path if necessary.

**Comment by jlolling** [comment]
Hi, you do not have to use the Windows path delimiters. Java translates the UNIX style path and use this for Windows just like Windows style path declarations.
/var/opt/talend/etl/config/manage.dev will work on Windows as well as on Linux!

**Comment by jlolling** [comment]
The only scenario in which you need real Windows path style is if you call external programs and work with the Windows shell.

**Comment by Nibbler73** [comment]
Hi Jan,

thanks for the quick reply. If I remove the 2nd `file_` line, the file does not get loaded.

The exernal file is a text-file this content, it's not a script or executable program:

```
MANAGE_SCHEMA_DB_server=dbserver.example.com
MANAGE_SCHEMA_DB_user=example-user
MANAGE_SCHEMA_DB_password=example-password
```

**Comment by jlolling** [comment]
It should work meanwhile. Could you please check it again. In my tests it works well.

**Comment by Nibbler73** [comment]
I tried with version 5.0 of `tContextInput`, but the behaviour seems to not change.

This properties file works on my Windows based Studio:

```
file_linux_manageSchema=/var/opt/talend/etl/config/manage.dev
file_windows_manageSchema=c:/var/opt/talend/etl/config/manage.dev
```

This file does not:

```
file_linux_manageSchema=/var/opt/talend/etl/config/manage.dev
#file_windows_manageSchema=c:/var/opt/talend/etl/config/manage.dev
```

**Comment by jlolling** [comment]
I cannot reproduce this. I am working currently also on a Windows based workstation and also on a Mac and the same path works well. I do not have to use windows dedicated path.
